// Lista de cartões extraída da base real do admin dashboard (Supabase, projeto
// "Viagente Adm", tabela `cartoes` — 194 cartões cadastrados) — muito mais completa
// do que a lista estática que existia no formulário público de diagnóstico.
// Busca fuzzy replicada de v0-viajente-admin-dashboard (app/diagnostico/form/page.tsx).

export const CARTOES_CREDITO = [
  "Ágora Visa Infinite",
  "Amazon Prime Mastercard Platinum",
  "Amazon.com.br Mastercard Platinum",
  "Azul Itaú Skyline Mastercard Black",
  "Banco do Brasil Altus Liv Visa Infinite",
  "Banco do Brasil Altus Visa Infinite Cashback",
  "Banco do Brasil Altus Visa Infinite Pontos",
  "Banco do Brasil ELO Diners Club Cashback",
  "Banco do Brasil ELO Diners Club Pontos",
  "Banco do Brasil ELO Grafite Estilo Pontos",
  "Banco do Brasil ELO Nanquim Estilo Cashback",
  "Banco do Brasil ELO Nanquim Estilo Pontos",
  "Banco do Brasil Fácil Visa Internacional",
  "Banco do Brasil GOL Smiles Visa Infinite",
  "Banco do Brasil GOL Smiles Visa Platinum",
  "Banco do Brasil Mastercard Black Cashback",
  "Banco do Brasil Mastercard Black Pontos",
  "Banco do Brasil Petrobras Visa Internacional",
  "Banco do Brasil Visa Infinite Cashback",
  "Banco do Brasil Visa Infinite Pontos",
  "Banco do Brasil Visa Platinum Estilo Cashback",
  "Banco do Brasil Visa Platinum Estilo Pontos",
  "Banco do Nordeste Visa Infinite",
  "Banco do Nordeste Visa Platinum",
  "Banescard Absoluto Visa Infinite",
  "Banescard Visa Infinite",
  "Banescard Visa Platinum",
  "Banese Card ELO Nanquim",
  "Banpará Mastercard Black",
  "Banpará Mastercard Black Exclusive",
  "Banpará Mastercard Platinum",
  "Banrisul Mastercard Black",
  "Banrisul Mastercard Platinum",
  "Banrisul Visa Infinite",
  "Banrisul Visa Platinum",
  "Bradesco Aeternum Visa Infinite",
  "Bradesco American Express Centurion",
  "Bradesco American Express Gold Card",
  "Bradesco American Express The Platinum Card",
  "Bradesco ELO Diners Club",
  "Bradesco ELO Nanquim",
  "Bradesco GOL Smiles Visa Infinite",
  "Bradesco GOL Smiles Visa Platinum",
  "Bradesco Mastercard Black",
  "Bradesco Principal Visa Infinite",
  "Bradesco Visa Infinite",
  "BRB Connect Mastercard Internacional",
  "BRB Dux Visa Infinite",
  "BRB Mastercard Black",
  "BRB Mastercard Platinum",
  "BRB Visa Infinite",
  "BRB Visa Platinum",
  "BTG Pactual Mastercard Black",
  "BTG Pactual Mastercard Platinum",
  "BTG Pactual TAP Mastercard Black",
  "BTG Pactual Ultrablue Mastercard Black",
  "Buscapé Mastercard Gold",
  "BV Livre Visa Gold",
  "BV Único Visa Infinite",
  "C6 Bank Graphene Mastercard World Legend",
  "C6 Bank Mastercard Platinum",
  "C6 Carbon Mastercard Black",
  "Caixa ELO Diners Club",
  "Caixa ELO Grafite",
  "Caixa ELO Nanquim",
  "Caixa Ícone Visa Infinite",
  "Caixa Mastercard Black",
  "Caixa Sim ELO Nacional",
  "Caixa Sim Visa Nacional",
  "Caixa Visa Infinite",
  "Cresol Mastercard Black",
  "Cresol Mastercard Internacional",
  "Cresol Mastercard Platinum",
  "Genial Mastercard Black",
  "Genial Mastercard Platinum",
  "Inter Mastercard Black Win",
  "Inter Mastercard Gold",
  "Inter Mastercard Platinum",
  "Inter Prime Mastercard Black",
  "Inter Win Mastercard Black",
  "Itaú Ayrton Senna Mastercard Platinum",
  "Itaú Ayrton Senna Visa Platinum",
  "Itaú Azul Visa Infinite",
  "Itaú Compre Bem Mastercard Internacional",
  "Itaú Iti Visa Platinum",
  "Itaú Latam Pass Mastercard Black",
  "Itaú Latam Pass Visa Infinite",
  "Itaú Magalu Visa Platinum",
  "Itaú Mastercard Platinum",
  "Itaú Pão de Açúcar Mastercard Black",
  "Itaú Pão de Açúcar Mastercard Internacional",
  "Itaú Pão de Açúcar Mastercard Platinum",
  "Itaú Pão de Açúcar Visa Internacional",
  "Itaú Personnalité Mastercard Black",
  "Itaú Personnalité Mastercard Black Cashback",
  "Itaú Personnalité Mastercard Platinum",
  "Itaú Personnalité Mastercard World Legend",
  "Itaú Personnalité Visa Infinite",
  "Itaú Personnalité Visa Signature",
  "Itaú Private Mastercard World Legend",
  "Itaú Private Visa Infinite",
  "Itaú Samsung Visa Platinum",
  "Itaú The One Mastercard Black Personnalité",
  "Itaú The One Mastercard Black Private",
  "Itaú Uniclass Mastercard Black",
  "Itaú Uniclass Visa Infinite",
  "Itaú Uniclass Visa Signature",
  "Itaú Visa Infinite Privilege",
  "Itaú Visa Platinum",
  "Itaú Vivo Mastercard Platinum",
  "Mercado Pago Visa Gold",
  "Motorola Dimo Visa Internacional",
  "Neon Visa Internacional",
  "Nomad Explorer Visa Infinite",
  "Novucard Visa Internacional",
  "Nubank Mastercard Gold",
  "Nubank Ultravioleta Mastercard Black",
  "Ourocard ELO Diners Club Cashback",
  "Ourocard ELO Diners Club Pontos",
  "Ourocard ELO Grafite Estilo Pontos",
  "Ourocard ELO Nanquim Estilo Cashback",
  "Ourocard ELO Nanquim Estilo Pontos",
  "Ourocard Fácil Visa Internacional",
  "Ourocard Mastercard Black Cashback",
  "Ourocard Mastercard Black Pontos",
  "Ourocard Visa Infinite Cashback",
  "Ourocard Visa Infinite Pontos",
  "Ourocard Visa Platinum Estilo Cashback",
  "Ourocard Visa Platinum Estilo Pontos",
  "PagBank Visa Internacional",
  "PicPay Card Mastercard Internacional",
  "PicPay Epic Mastercard Black",
  "PicPay Mastercard Black",
  "PicPay Mastercard Platinum",
  "Porto Bank Mastercard Black",
  "Porto Bank Mastercard Platinum",
  "Porto Bank Visa Infinite",
  "Porto Bank Visa Infinite Privilege",
  "Porto Bank Visa Platinum",
  "Recargapay Mastercard Black",
  "RecargaPay Mastercard Internacional",
  "Recargapay Mastercard Platinum",
  "RecargaPay Titan Mastercard Black",
  "Revolut Metal Visa Infinite",
  "Revolut Ultra Visa Infinite",
  "Rico One Visa Infinite Cashback",
  "Rico One Visa Infinite Pontos",
  "Rico Visa Infinite Cashback",
  "Rico Visa Infinite Pontos",
  "Safra Investidor Visa Infinite",
  "Safra Visa Infinite",
  "Santander AAdvantage Mastercard Black",
  "Santander American Express Centurion",
  "Santander American Express The Platinum Card",
  "Santander Elite Mastercard Platinum",
  "Santander Elite Mastercard Platinum Cashback",
  "Santander Elite Visa Signature",
  "Santander Elite Visa Signature Cashback",
  "Santander GOL Smiles Visa Infinite",
  "Santander GOL Smiles Visa Platinum",
  "Santander Unique Mastercard Black Cashback",
  "Santander Unique Mastercard Black Pontos",
  "Santander Unique Visa Infinite Cashback",
  "Santander Unique Visa Infinite Pontos",
  "Santander Unlimited Mastercard Black",
  "Santander Unlimited Visa Infinite",
  "Sem Parar Mastercard Platinum",
  "Sem Parar Visa Infinite",
  "Sem Parar Visa Platinum",
  "Sicoob Mastercard Black",
  "Sicoob Mastercard Black Merit",
  "Sicoob Mastercard Platinum",
  "Sicoob Visa Infinite",
  "Sicoob Zenith Visa Infinite",
  "Sicredi Mastercard Black",
  "Sicredi Mastercard Platinum",
  "Sicredi Visa Infinite",
  "Sicredi Visa Platinum",
  "Sisprime Mastercard Black",
  "Sisprime Mastercard Platinum",
  "Sofisa Direto Mastercard Black",
  "Trigg Visa Internacional",
  "Unicred Ímpar Visa Infinite",
  "Unicred Mastercard Platinum",
  "Unicred Visa Infinite",
  "Unicred Visa Infinite Privilege",
  "Unicred Visa Platinum",
  "XP Legacy Visa Infinite",
  "XP One Visa Infinite Cashback",
  "XP One Visa Infinite Pontos",
  "XP Visa Infinite Cashback",
  "XP Visa Infinite Pontos",
  "XP Visa Infinite Privilege",
  "Outro (customizado)",
]

function normalizar(str: string): string {
  return str
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .toLowerCase()
}

/** Match fuzzy multi-palavra, ignorando acento e caixa — mesma lógica do admin dashboard. */
export function matchCartao(nome: string, busca: string): boolean {
  if (!busca.trim()) return true
  const nomeNorm = normalizar(nome)
  return normalizar(busca)
    .trim()
    .split(/\s+/)
    .every((palavra) => nomeNorm.includes(palavra))
}
